### ISSUE TITLE
Ошибка в тексте лабы 2 

### ISSUE THREAD

**Issue by yerseg** [CryptoCourse/CryptoLabs#4]
https://github.com/CryptoCourse/CryptoLabs/blob/master/Impl/HashAndEnemies.md
![rrVtfuv3e0s](https://user-images.githubusercontent.com/43613813/77226518-1201fb00-6b8a-11ea-980e-ce7a2e0284f4.jpg)

Вместо H там Pi. Это участок с описанием второго алгоритма. Отдебажить это мне удалось за 2 дня. Спасибо.

**Comment by Fasjeit** [comment]
В конец каждый лабы есть ссылки на первоисточники. Там всегда можно проверить правильность алгоритмов. Также перед тем как прогать желательно понимать, зачем нужен каждый отдельный шаг алгоритма.

**Comment by Fasjeit** [comment]
И там должен быть не Pi, а скорее Pi*H
